package se.lexicon.sprintailecture.service;

import org.springframework.ai.openai.OpenAiChatModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class OpenAIServiceImpl implements  OpenAIService {

    OpenAiChatModel openAiChatModel;

    @Autowired
    public OpenAIServiceImpl(OpenAiChatModel openAiChatModel) {
        this.openAiChatModel = openAiChatModel;
    }

    @Override
    public String chat(String question) {
        // add system instruction
        // calling functions
        // process and customise the response
        // ...

        // call method returns the response that generated by openai models
        return openAiChatModel.call(question);
    }

}
